version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]
