version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: blog_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: blog_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: blog_rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ connection
      - "15672:15672" # RabbitMQ management UI
    restart: unless-stopped

volumes:
  mongo_data:
